### ISSUE TITLE
how to do run this image with docker-compose?

### ISSUE THREAD

**Issue by dawang1024** [siomiz/SoftEtherVPN#104]
**how to do run this image with docker-compose?**

**Please provide a test case,
Thank you very much;**

**Comment by belegnar** [comment]
```
$ cat docker-compose.yml
version: "3"

services:
  softethervpn:
    image: siomiz/softethervpn:debian
    restart: always
    volumes:
      - ./vpn_server.config:/usr/vpnserver/vpn_server.config
      - /dev/net:/dev/net:z
    cap_add:
      - NET_ADMIN
    ports:
      - 500:500/udp
      - 4500:4500/udp
      - 1701:1701/tcp
      - 1194:1194/udp
      - 5555:5555/tcp
 ```

**Comment by Neo-Desktop** [comment]
```yaml
version: "3"
services:
  softether:
    image: siomiz/softethervpn
    volumes:
      - ./softether/vpn_server.config:/usr/vpnserver/vpn_server.config
    cap_add:
      - NET_ADMIN
    ports:
      - 443:443/tcp
      - 500:500/udp
      - 4500:4500/udp
      - 1701:1701/tcp
      - 1194:1194/udp
      - 5555:5555/tcp
```
