### ISSUE TITLE
iptables v1.4.21: can't initialize iptables table `filter': Permission denied (you must be root)

### ISSUE THREAD

**Issue by tlightsky** [siomiz/SoftEtherVPN#19]
```
ssp_1  | # [initial setup OK]
ssp_1  | iptables v1.4.21: can't initialize iptables table `filter': Permission denied (you must be root)
ssp_1  | Perhaps iptables or your kernel needs to be upgraded.
```

docker-compose:
```yml
ssp:
  image: siomiz/softethervpn
  ports:
   - "500:500/udp"
   - "4500:4500/udp"
   - "1701:1701/tcp"
  environment:
   - PSK=123
   - USERS=abc:def
  restart: always
```
