### ISSUE TITLE
Softether on Ubuntu Docker high CPU

### ISSUE THREAD

**Issue by deeztek** [siomiz/SoftEtherVPN#87]
Hi,

I'm having an issue with a softether container on Ubuntu 18.04. Looking at top, I'm seeing 6 vpncmd processes taking up all the CPU cycles. Please see below:

![image](https://user-images.githubusercontent.com/17934095/99998326-8382f080-2d8c-11eb-8d9c-e818972bb824.png)

Any idea what's happening here or where to look for a problem?

Here's my docker compose:

```
version: "3"

networks:
  proxy:
    external: true

services:
  softethervpn:
    image: siomiz/softethervpn
    container_name: softethervpn
    environment:
      #- PUID=$PUID
      #- PGID=$GUID
      - TZ=$TZ
      - UMASK_SET=022 #optional
    volumes:
      - ./softether_config/vpnserver/vpn_server.config:/usr/vpnserver/vpn_server.config
      - ./softether_config/server_log:/usr/vpnserver/server_log
      - ./certs:/certs
    networks:
      - proxy
    cap_add:
      - NET_ADMIN
    ports:
      #- 443:443/tcp
      - 992:992/tcp
      - 1194:1194/udp
      - 5555:5555/tcp
      - 1701:1701/udp
      - 500:500/udp
      - 4500:4500/udp
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.services.sofethervpn.loadBalancer.server.port=443"
      - "traefik.tcp.routers.softethervpn.entrypoints=https"
      - "traefik.tcp.routers.softethervpn.rule=HostSNI(`ecvpn.$DOMAIN`)"
      - "traefik.http.routers.softethervpn.entrypoints=https"
      - "traefik.http.routers.softethervpn.rule=Host(`ecvpn.$DOMAIN`)"
      - "traefik.http.routers.softethervpn.tls=true"
      - "traefik.http.routers.softethervpn.tls.certresolver=le"
      - "traefik.tcp.routers.softethervpn.tls.passthrough=true"

    restart: unless-stopped

```
Here's the Softether Version:

`Server product name: "SoftEther VPN Server (64 bit) (Open Source)", Server version: 434, Server build number: 9745`

Thanks
