### ISSUE TITLE
docker-compose environment "USERS" does not work

### ISSUE THREAD

**Issue by macaron** [siomiz/SoftEtherVPN#92]
docker-compose environment "USERS" does not work 😭 

```yml
version: '3.7'

services:
  vpn:
    image: siomiz/softethervpn:9745-alpine
    ports:
      - "500:500"
      - "4500:4500"
      - "1701:1701"
    environment:
      - USERS=user1:password1;user2:password2
      - SPW=mysoftetherserver39
      - HPW=mysoftetherhub39
      - PSK=vpn
    privileged: true
    restart: always
    volumes:
      - ./logs:/usr/vpnserver
```

When execute `docker-compose up -d`, cause restart loop…

```sh
$ docker-compose logs -f
vpn_1  | # ========================
vpn_1  | # <use the password specified at -e USERS>
vpn_1  | # ========================
vpn_1  | /usr/bin/vpnserver: line 2: /usr/vpnserver/vpnserver: not found
```

## my machine
Ubuntu 20.04
Docker version 20.10.6, build 370c289
docker-compose version 1.29.1, build c34c88b2

Thank you.
